import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { FollowCursor, OverlayNavbar } from "@/components";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: "400",
});
const inverse = localFont({
  src: "../public/fonts/inverse.ttf",
  variable: "--font-inverse",
});

const futura = localFont({
  src: "../public/fonts/futura.ttf",
  variable: "--font-futura",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-b from-background to-black h-screen ${inter.className} ${inverse.variable} ${futura.variable}`}
      >
        <FollowCursor />
        <OverlayNavbar />
        {children}
      </body>
    </html>
  );
}
