import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { FollowCursor, OverlayNavbar } from "@/components";
import { RootLayout as PortfolioLayout } from "./_root/layout";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: "400",
});
const inverse = localFont({
  src: "../public/fonts/inverse.ttf",
  variable: "--font-inverse",
});

const futura = localFont({
  src: "../public/fonts/futura.ttf",
  variable: "--font-futura",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`dark h-screen bg-gradient-to-b from-bg-primary to-black ${inter.className} ${inverse.variable} ${futura.variable} ${poppins.variable}`}
      >
        <PortfolioLayout />
        <FollowCursor />
        <OverlayNavbar />
      </body>
    </html>
  );
}
